name: WhoIsThat
main: net.mcviral.dev.plugins.whoisthat.main.WhoIsThat
version: 1.0
author: comdude2
commands:
   whoisthat:
      description: This is this plugin's main command.
      usage: /<command> help
      permission: whoisthat.inquire
      permission-message: You don't have the required permission to perform this command.